Develop
Swarmies/sap-core pull request #32
Opened 2022-06-02 05:53 UTC by BAbate

# Description

This is basic ER relationship diagram that is based on UML diagram. It's dependent on MermaidJS

Fixes # (issue)
None 

## Type of change

Please delete options that are not relevant.

- new features 
- this change itself is documentation that developers refer to construct the database 

# How Has This Been Tested?

It has been tested locally and on live editor. A link is included to help the developer replicate the same test 

**Test Configuration**:
N/A

# Checklist:

- [ yes] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [ yes ] I have commented on my code, particularly in hard-to-understand areas
- [ yes] I have made corresponding changes to the documentation
- [ N/A] My changes generate no new warnings
- [ N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A ] New and existing unit tests pass locally with my changes
- [N/A ] Any dependent changes have been merged and published in downstream modules

2022-06-02 12:55 UTC, kirubeltadesse commented
Nice job BK. Could be remove this file
[Doc/.UML_diagram.md.swp](https://github.com/Swarmies/sap-web/pull/32/files#diff-67a0786a8ce700d94a6c17142b8e15e1ea67e10bf99cd63701b2cc3c41f23ae7)

2022-06-04 00:47 UTC, kirubeltadesse reviewed
Here is an additional comment

2022-06-04 00:47 UTC, kirubeltadesse commented on Doc/ER_diagram.md
> +        SIGNIN {
Let's remove this table because it is redundant.

2022-06-04 00:47 UTC, kirubeltadesse commented on Doc/ER_diagram.md
> +          ADMIN ||--o{ EVENTS : posts
add a `string password` field here

2022-06-04 01:32 UTC, Getnet12 reviewed
It's a suggestion Kira come up with while we were talking.

2022-06-04 01:32 UTC, Getnet12 commented on Doc/ER_diagram.md
> +# This diagram represents the ER relationship diagram among the entities below
Add a title and make the rest of the information a paragraph: for better formatting.

2022-06-04 01:32 UTC, Getnet12 commented on Doc/ER_diagram.md
> +            string course
change it courses instead of course.

2022-06-04 05:23 UTC, BAbate commented on Doc/ER_diagram.md
> +# This diagram represents the ER relationship diagram among the entities below
Okay good

2022-06-04 05:23 UTC, BAbate commented on Doc/ER_diagram.md
> +            string course
Good.

2022-06-04 05:26 UTC, BAbate commented on Doc/ER_diagram.md
> +          ADMIN ||--o{ EVENTS : posts
The first section represents Entity relationships and each constitutes its own table. Do you mean to have a Password entity? or if you are referring to string password, let me know the table so I can add it@kirubeltadesse

2022-06-04 05:26 UTC, BAbate commented on Doc/ER_diagram.md
> +        SIGNIN {
okay good.

2022-06-04 16:41 UTC, kirubeltadesse commented on Doc/ER_diagram.md
> +            string userName
Sorry, I mean add the password here. Next to the `userName`

2022-06-04 16:41 UTC, kirubeltadesse commented on Doc/ER_diagram.md
> +          ADMIN ||--o{ EVENTS : posts
I understand. clicked at the wrong place by mistake :)

2022-06-06 17:45 UTC, dinaolmelak requested changes

2022-06-06 17:45 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +        WEEKDAYS {
<img width="315" alt="Screen Shot 2022-06-06 at 12 34 25 PM" src="https://user-images.githubusercontent.com/32272045/172214454-b47efdb0-bb2a-4e13-8158-b9619626946f.png">

Should we add an entry for 'week' here?

2022-06-06 17:45 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +        CALENDAR {
Doesn't the admin need access to the calendar db?

2022-06-07 14:19 UTC, kirubeltadesse commented on Doc/ER_diagram.md
> +        CALENDAR {
That will be definitely higher on MVC level not do the db level!

2022-06-11 04:28 UTC, closed without merging

2022-06-16 23:48 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +            int user_id PK
The datatype of user_id seems to be inconsistent. It is an int datatype here but on STUDENT, MENTOR and SIGNIN it seems to be of string data type

2022-06-16 23:48 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +            string Jnumber
can we set this to camel case naming convention? (i.e string jNumber)

2022-06-16 23:48 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +            int mentor_id PK
The data type of `mentor_id` is int here but under EVENTS it is a string.

2022-06-16 23:48 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +            string Jnumber
Can we also set the data type of jNumber to `int`?

2022-06-17 00:16 UTC, kirubeltadesse commented on Doc/ER_diagram.md
> +            int user_id PK
@dinaolmelak this is closed PR?

2022-06-17 22:31 UTC, dinaolmelak commented on Doc/ER_diagram.md
> +            int user_id PK
Gotcha, I have added these changes to my pull request #43