update circleCI to use docker
Swarmies/sap-core pull request #36
Opened 2022-06-04 17:47 UTC by kirubeltadesse

# Description

This is updating circleCI to use the docker images created for this project. In order to properly check and test the code before merging. 

Fixes #34 

## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I am testing this code if it works on my forked branch.

2022-06-15 03:51 UTC, dinaolmelak reviewed
LGTM

2022-06-15 03:55 UTC, dinaolmelak commented on .circleci/config.yml
> +              auth:
Are you configuring it to use your dockerhub?

2022-06-16 13:46 UTC, kirubeltadesse commented on .circleci/config.yml
> +              auth:
Yes, I have pushed the images to docker hub and it will be pulling them. The circleci command are different. I need to refer to the right command and spin the containers for test in circleci 🤯

2022-06-16 16:00 UTC, Getnet12 approved these changes
Looks good to me.

2022-06-16 23:25 UTC, dinaolmelak reviewed
LGTM!

2022-06-16 23:26 UTC, dinaolmelak approved these changes

2022-06-27 16:05 UTC, dinaolmelak commented
I noticed that you have multiple commits
<img width="883" alt="Screen Shot 2022-06-27 at 11 04 53 AM" src="https://user-images.githubusercontent.com/32272045/175984412-89f1e090-0317-44ca-938e-dd6b2de7d999.png">

can you merge these together?

2022-06-27 16:08 UTC, dinaolmelak requested changes
<img width="883" alt="Screen Shot 2022-06-27 at 11 04 53 AM" src="https://user-images.githubusercontent.com/32272045/175984412-89f1e090-0317-44ca-938e-dd6b2de7d999.png">

Number of commits changed?

2022-06-27 16:10 UTC, kirubeltadesse commented
> I noticed that you have multiple commits <img alt="Screen Shot 2022-06-27 at 11 04 53 AM" width="883" src="https://user-images.githubusercontent.com/32272045/175984412-89f1e090-0317-44ca-938e-dd6b2de7d999.png">
> 
> can you merge these together?

Yes, there is a bug that I need to fix. I have already fixed the commit message locally.

2022-06-27 16:16 UTC, dinaolmelak commented
So 

> > I noticed that you have multiple commits <img alt="Screen Shot 2022-06-27 at 11 04 53 AM" width="883" src="https://user-images.githubusercontent.com/32272045/175984412-89f1e090-0317-44ca-938e-dd6b2de7d999.png">
> > can you merge these together?
> 
> Yes, there is a bug that I need to fix. I have already fixed the commit message locally.

Have you pushed the fixes? cause I still see multiple commits on my end.

2022-06-27 16:22 UTC, kirubeltadesse commented
Sure, once the bug is fixed. I will push my updates and you will get to see it :) @dinaolmelak

2022-06-27 16:24 UTC, dinaolmelak commented
Awesome bro, thank you for the Update 👍🏽

2022-06-27 16:24 UTC, dinaolmelak approved these changes

2022-06-27 16:26 UTC, kirubeltadesse reviewed
Needs a bug fix *DON"T MERGE*

2022-06-27 16:30 UTC, dinaolmelak submitted a review, later dismissed
<img width="883" alt="Screen Shot 2022-06-27 at 11 04 53 AM" src="https://user-images.githubusercontent.com/32272045/175984412-89f1e090-0317-44ca-938e-dd6b2de7d999.png">

- [ ] The number of commits changed
- [ ] Bugs Fixed

2022-10-06 00:25 UTC, kirubeltadesse reviewed
Partially Commit for now :)

2022-10-06 00:28 UTC, merged