create frontend using TypeScript and add container configuration
Swarmies/sap-core pull request #48
Opened 2022-10-10 02:09 UTC by kirubeltadesse

# Description

Reorganized the structure of the code. Add a `.devcontainer` configuration   

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I have tested that It works locally.

2022-10-11 18:29 UTC, dinaolmelak requested changes

2022-10-11 18:29 UTC, dinaolmelak commented on .gitignore
> -/data
does this directory need to be removed?

2022-10-11 22:52 UTC, kirubeltadesse commented on .gitignore
> -/data
Yes, we don't have to keep track of that directory anymore because it is can be built from Django automatically. That is generated as a result of the postgrad database.

2022-10-12 16:26 UTC, dinaolmelak approved these changes
LGTM!

2022-10-12 16:47 UTC, merged